---
- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Git client installation
      become: true
      apt:
        name: git
        update_cache: yes

    - name: Fetch the latest version of application code
      become: true
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
